articles:
    type:     rest
    resource: AppBundle\Controller\ArticleController

tags:
    type:     rest
    resource: AppBundle\Controller\TagController

user:
    type:     rest
    resource: AppBundle\Controller\UserController